### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by cmatskas** [relayr/csharp-sdk#1]
Hi, any reason why there's no NuGet package for the C# SDK? Would you like me to create one?

**Comment by SmbatYeranyan** [comment]
Hi,
We noticed you already made the change in the Pull Request. We will merge it soon as possible.

Thanks!

**Comment by cmatskas** [comment]
@SmbatYeranyan Hi, What I asked was why the whole PCL is not available as a NuGet package. Yes, the other packages in the solution have been updated but I would like to make a NuGet package for relayr so that other users can easily add it to their solutions.

**Comment by SmbatYeranyan** [comment]
@cmatskas Apologies for the misunderstand, I was under the impression we had the dependency already in place. Please proceed with the creation of the NuGet package.
Thanks!

**Comment by cmatskas** [comment]
No problem,

I will proceed with this soon :)

Thanks,
CM

On Fri, Oct 23, 2015 at 9:46 AM, Smbat Yeranyan <notifications@github.com>
wrote:

> @cmatskas <https://github.com/cmatskas> Apologies for the misunderstand,
> I was under the impression we had the dependency already in place. Please
> proceed with the creation of the NuGet package.
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/relayr/csharp-sdk/issues/1#issuecomment-150515971>.
>



-- 
Christos Matskas
IT Director
SoftwareLounge
